---
description: Pipeline for 1Password Item Usages Events Reporting
processors:
  - set:
      field: ecs.version
      value: '1.11.0'
on_failure:
  - set:
      field: error.message
      value: '{{ _ingest.on_failure_message }}'